### ISSUE TITLE
Hishel Controller Force-Cache Feature

### ISSUE THREAD

**Issue by ratzrattillo** [karpetrosyan/hishel#198]
I really enjoy using Hishel due to its uncomplicated integration with httpx! Nice work!

Currently, i often set the force cache extension in my requests, if i definitely want to cache them
```python
extensions={"force_cache": True}
```
Unfortunately, there seems to be no way to configure force_cache on controller level. This would really be neat!

It would also be great, if i could decide depending on the response content (response body, not only headers), if it should be cached or not.
This might be implemented using event hooks.

This would be helpful in many situations where the server sends no-chache/no-store or Cache-Control headers back, preventing hishel from storing them.

Thanks for considering!

**Comment by karpetrosyan** [comment]
Hi!

Indeed, you are correct. It is definitely something we should consider adding into the controllers.

Now you can do that by just overriding a few controller methods in the following manner:

```python
from httpcore import Request, Response
from hishel import Controller
from hishel import CacheClient


class ForceCacheController(Controller):
    def is_cachable(self, request: Request, response: Response) -> bool:
        return True

    def construct_response_from_cache(
        self, request: Request, response: Response, original_request: Request
    ) -> Response | Request | None:
        # Only do not use the cache if the vary headers does not match
        # This would prevent the cache to use a response that was meant for another request
        # For example, if the original request had the header "Accept: application/json"
        # but the current request has "Accept: text/html", the cache should not be used
        if not self._validate_vary(request=request, response=response, original_request=original_request):
            return None

        return True


client = CacheClient(controller=ForceCacheController())
```

However, it makes perfect sense to have a boolean to simply enable or disable force caching for the entire controller.

All we need to do is accept the `force_cache` option in the Controller constructor. After that, we can check the controoler force_cache property in addition to the force_cache extension.

So instead of

```python
if request.extensions.get("force_cache", False):
    return True
```

Shoule be

```python
if self.force_cache or request.extensions.get("force_cache", False):
    return True
```

Am I right?

Would you like to issue a pull requests adding this feature?

> It would also be great, if i could decide depending on the response content (response body, not only headers), if it should be cached or not.
This might be implemented using event hooks.

Here, we think almost identically.

I had such idea here: https://github.com/karpetrosyan/hishel/issues/112#issuecomment-1820273162
Do you have any thoughts for how you would want to see such functionality?

**Comment by karpetrosyan** [comment]
We can also instead of:

```python
if self.force_cache or request.extensions.get("force_cache", False):
    return True
```

Write something like:

```
force_cache = request.extensions.get("force_cache", None)

if (force_cache if force_cache is not None else self.force_cache):
    ...
```

To simply let the extensions override the controllers settings.

**Comment by ratzrattillo** [comment]
I will issue a pull request to solve the issue. Thanks for your hints!

**Comment by ratzrattillo** [comment]
Suggestion of fix in https://github.com/karpetrosyan/hishel/pull/204
@karpetrosyan  Feel free to edit the pull request at will, as you have better understanding hishel than i have ;)

**Comment by ratzrattillo** [comment]
Thank you for merging! I will close this issue as it has been fixed in https://github.com/karpetrosyan/hishel/pull/204

The topic of "caching depending on response content" was moved to issue https://github.com/karpetrosyan/hishel/issues/205
