### ISSUE TITLE
Cache doesn't seem to work?

### ISSUE THREAD

**Issue by Ravencentric** [karpetrosyan/hishel#203]
I tried hishel and httpx and didn't notice any speedup which lead me to benchmark it and benchmark confirms it. Am I doing something wrong here? I've read the docs but can't really grasp what's going wrong here. Below are the test scripts I used.

```py
# cache.py
import hishel

query = """
query ($id: Int) {
  Media (id: $id, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
  }
}
"""

variables = {"id": 16498}
url = "https://graphql.anilist.co"

for i in range(5):
    hishel.CacheClient(controller=hishel.Controller(cacheable_methods=["POST"])).post(
        url, json={"query": query, "variables": variables}
    )

```

```py
# nocache.py
import httpx

query = """
query ($id: Int) {
  Media (id: $id, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
  }
}
"""

variables = {"id": 16498}
url = "https://graphql.anilist.co"

for i in range(5):
    httpx.Client().post(
        url, json={"query": query, "variables": variables}
    )
```

### Benchmark
```
❯ hyperfine "python cache.py" "python nocache.py"
Benchmark 1: python cache.py
  Time (mean ± σ):      3.942 s ±  0.251 s    [User: 0.197 s, System: 0.549 s]
  Range (min … max):    3.610 s …  4.448 s    10 runs
 
Benchmark 2: python nocache.py
  Time (mean ± σ):      3.230 s ±  0.678 s    [User: 0.248 s, System: 0.705 s]
  Range (min … max):    2.216 s …  4.044 s    10 runs

Summary
  python nocache.py ran
    1.22 ± 0.27 times faster than python cache.py
    ```

**Comment by karpetrosyan** [comment]
It actually not uses the response from the cache and here is why:

We should add the line **print(response.headers["cache-control"])** and we would see:

```
no-cache, private
```

Because Hishel is smart and can understand cache headers defined in the [RFC9111][https://www.rfc-editor.org/rfc/rfc9111.html], hishel will respect them.

[RFC says](https://www.rfc-editor.org/rfc/rfc9111.html#name-no-cache-2):

*The no-cache response directive, in its unqualified form (without an argument), indicates that the response MUST NOT be used to satisfy any other request without forwarding it for validation and receiving a successful response; see [Section 4.3](https://www.rfc-editor.org/rfc/rfc9111.html#validation.model). This allows an origin server to prevent a cache from using the response to satisfy a request without contacting it, even by caches that have been configured to send stale responses. The qualified form of the no-cache response directive, with an argument that lists one or more field names, indicates that a cache MAY use the response to satisfy a subsequent request, subject to any other restrictions on caching, if the listed header fields are excluded from the subsequent response or the subsequent response has been successfully revalidated with the origin server (updating or removing those fields). This allows an origin server to prevent the reuse of certain header fields in a response, while still allowing caching of the rest of the response. The field names given are not limited to the set of header fields defined by this specification. Field names are case-insensitive. This directive uses the quoted-string form of the argument syntax. A sender SHOULD NOT generate the token form (even if quoting appears not to be needed for single-entry lists).*

*Note: The qualified form of the directive is often handled by caches as if an unqualified no-cache directive was received; that is, the special handling for the qualified form is not widely implemented.*

If you will look at .cache/hishel directory, you would see the cached response, but since there is a no-cache header sent by the server, hishel can not violate the RFC and use that without the verification, so it tries to verify the response, but fails because there is no ETag or Last-Modified headers in the response (see https://www.rfc-editor.org/rfc/rfc9111.html#name-sending-a-validation-reques)

Hishel provides a mechanism to disable the RFC headers, to simply ignore them. You can do it like so:

```python
# cache.py
import hishel

query = """
query ($id: Int) {
  Media (id: $id, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
  }
}
"""

variables = {"id": 16498}
url = "https://graphql.anilist.co"

controller = hishel.Controller(cacheable_methods=["POST"])
storage = hishel.FileStorage(ttl=120) # 2 minutes
client = hishel.CacheClient(
    controller=controller,
    storage=storage
)

for i in range(5):
    response = client.post(
        url, json={"query": query, "variables": variables},
        extensions={"force_cache": True}
    )

    print(response.extensions["from_cache"])
```

**Comment by karpetrosyan** [comment]
It is critical to remember that hishel fully follows RFC9111, and cache operates precisely like a browser's cache, thus it will not cache resposes that the server has requested not to cache.

However, you can use "stupid caching" without any rules by supplying the force_cache extension. If the force_cache extension is set to true, hishel will ignore RFC restrictions and instead use [storages](https://hishel.com/advanced/storages/) to cache the answer in the cloud, files, redis, sqlite, or memory.

**Comment by Ravencentric** [comment]
Thank you for the detailed answer!
