### ISSUE TITLE
Caching doesn't seem to work with proxies

### ISSUE THREAD

**Issue by RozeFound** [karpetrosyan/hishel#210]
It straight up doesn't even call `handle_async_request` even with `force_cache`

To reproduce:
1. Initialize default cache client
2. Add socks5 proxy to it (haven't tested with others)
3. See how requests completely ignore cache layer

**Comment by karpetrosyan** [comment]
Hi!

Could you please supply the code you used to add proxy to your client?

**Comment by RozeFound** [comment]
Yeah, sure!
Client creation code is:
```python
transport = httpx.AsyncHTTPTransport()
storage = hishel.AsyncFileStorage()
controller = hishel.Controller(force_cache=True)
cache_transport = hishel.AsyncCacheTransport(transport=transport, storage=storage, controller=controller)

proxies = {
	"all://": httpx.Proxy("socks5://localhost:25344")
}

async with httpx.AsyncClient(transport=cache_transport, proxies=proxies) as client:
	...
```

**Comment by RozeFound** [comment]
Setting proxy like this
```python
transport = httpx.AsyncHTTPTransport(proxy="socks5://localhost:25344")
...
cache_transport = hishel.AsyncCacheTransport(transport=transport, storage=storage, controller=controller)
```
Doesn't work either if you're curious

**Comment by karpetrosyan** [comment]
The first example will not work, and it's expected.
You are trying to mout **all://** with the proxy transport, and not with the cache + proxy transport so it maps **all://** with the regular **httpx.AsyncHTTPTransport**

Second example will work, but I think you also passing the proxies from the first example, so it will overwrite the default mounting and will send requests through the regular **AsyncHTTPTransport** instead of hishels transports.

```python
transport = httpx.AsyncHTTPTransport(proxy="https://localhost:25344")
controller = hishel.Controller(force_cache=True)
cache_transport = hishel.AsyncCacheTransport(transport=transport, controller=controller)

proxies = {
    "all://": httpx.Proxy("https://localhost:25344")
}
async with httpx.AsyncClient(
    transport=cache_transport,
    proxies=proxies
    ) as client:
    print(client._mounts)  # {all://: <httpx.AsyncHTTPTransport object>}
```

So you should either remove proxies to not overwrite the default transport, which is cache transport in the second example, or use the [**mounts**](https://www.python-httpx.org/advanced/proxies/#http-proxies) api like so

```python
transport = httpx.AsyncHTTPTransport(proxy="https://localhost:25344")
controller = hishel.Controller(force_cache=True)
cache_transport = hishel.AsyncCacheTransport(transport=transport, controller=controller)

mounts = {
    "all://": cache_transport
}

async with httpx.AsyncClient(mounts=mounts) as client:
    print(client._mounts)  # {all://: hishel._async._transports.AsyncCacheTransport object}
```

**Comment by RozeFound** [comment]
Maybe I should've slept more than 4 hours today... Sorry to spend your time, thanks for help!
