### ISSUE TITLE
RedisStorage - option to set ttl depending on cache directives

### ISSUE THREAD

**Issue by rprodhomme** [karpetrosyan/hishel#287]
We use RedisStorage, we haven't set a default `ttl` and we've noticed that keys are never evicted (which may lead to issues on redis as it may reach 100% of memory usage, depending on [eviction strategy](https://redis.io/docs/latest/develop/reference/eviction/)).

We would have expected the `ttl` to be set depending on the `max-age`, `max-stale`,... directives returned by the response instead of `None`.

If we want to avoid these keys being stored in redis with no ttl, the only option I can see in the code is to have an hardcoded `default_ttl` value (doc [here](https://github.com/Simon-Will/hishel/blob/904160f4bbc7278438054e2f57e8ba9daa077433/docs/advanced/storages.md#responses-ttl-in-redisstorage)). The issue here is that we wouldn't rely on the response directives, which mean we may cache responses for inadequate durations.

Is there something we're missing here? Looking at the code there's no `ttl` set depending on the directives returned by the response.

Note that we use the option `allow_stale=True` but I don't think it has an impact on our issue.

**Comment by rprodhomme** [comment]
Thanks for your reply!

> You should manually configure the Redis storage to remove responses after a specified TTL.

The issue with this approach is that we'll need to pick an arbitrary value for this TTL as we don't want these keys to live in redis forever.

If we pick a high value (1 day or more for instance) it means we'll probably store some keys for too long (because the combination of its `max-age` and `max-stale` of the response is lower than that), so iwe're not using efficiently our redis. We may too evict values too early (for instance if the `max-stale` is one week), so we may not cache as much as we could.

If we pick a lower value (1 hour for instance) it means we won't use caching for as long as we could have.

Having the tll set by default given the directives from the response would be more efficient, is that something that could be implemented in hishel?

We're moving from requests to httpx, so we thought about moving from requests-cache to hishel, to keep the same caching feature, and we'd like something like [this](https://requests-cache.readthedocs.io/en/stable/#headers-and-expiration) (expiration based on cache-control headers).

Thanks again for your work!

**Comment by karpetrosyan** [comment]
A quick question before I answer: do I understand correctly that you are using different max-stale values for different requests?

Like:

```python
client.get("https://www.example.org", headers={"Cache-Control": "max-stale=3600"}
client.get("https://www.example.org/other_resource", headers={"Cache-Control": "max-stale=7200"}
```

**Comment by rprodhomme** [comment]
> A quick question before I answer: do I understand correctly that you are using different max-stale values for different requests?
> 
> Like:
> 
> ```python
> client.get("https://www.example.org", headers={"Cache-Control": "max-stale=3600"}
> client.get("https://www.example.org/other_resource", headers={"Cache-Control": "max-stale=7200"}
> ```

No, we don't set Cache-Control headers on the request. When we create the client we just have:
```python
client = CacheClient(
        controller=Controller(allow_stale=True),
        storage=RedisStorage(client=Redis.from_url(...)),
    )
``` 

We'd just like the ttl being set depending on the response cache control header.

**Comment by karpetrosyan** [comment]
Okay, I see... The `max-stale` header directive is not something that the remote server sends with the response. Instead, it’s used by clients (on your side) to tell the caching server (in your case, Hishel) that you're okay with receiving a response that is stale for up to N seconds.

It's a bit confusing to me, what max-age and max-stale combination is, 

- The max-age (a response directive) is used to tell the client how long the response should be considered fresh.
- The max-stale (a request directive) is used to tell the caching server that you want to receive the response, even if it was considered stale N seconds ago.

It makes sense to set the max-age value to the TTL if you don’t store stale responses. I believe that’s what requests-cache does. However, Hishel doesn’t support this, as stale responses can be revalidated without transferring the entire response data again over the network. Additionally, if you are using allow_stale, setting the max-age value to the TTL doesn’t make sense, as it will never become stale.

I’d like to help you choose the right strategy for caching your responses, but I need a bit more context.

**Comment by rprodhomme** [comment]
You're right about `max-stale`, my mistake, sorry for the confusion, I was thinking about the `stale-if-error` directive that is sent by the response.

Basically what we would like is an option so the ttl is set according to the response directives (so the max of `max-age`, `stale-if-error`...) so the cache is available as long as it may be useful but gets evicted afterwards.

Is it a feature that would make sense to implement in hishel? We may help to introduce it if you think it's a good idea.

**Comment by karpetrosyan** [comment]
`stale-if-error` is an obsolete directive that should be ignored by new implementations. Please refer to the [latest caching specification](https://www.rfc-editor.org/rfc/rfc9111#name-cache-control) for current directives.

Anyway, it just specifies how long the response can be used while stale if the remote server responds with a 5xx status code. A very specific case, isn’t it?

It’s important to understand that there is no such thing as a useless cached response; every single entry in your cache has value. Here’s why...

- A response that became stale N days ago can still be very useful because, at any time, you can simply revalidate it and retrieve a fresh version without transferring the entire data. This process is called [revalidation](https://www.rfc-editor.org/rfc/rfc9111.html#section-4.3.1).
    Suppose you’ve downloaded a response of 100 MB, which has now become stale according to the server's max-age directive. You can still revalidate that response without downloading the entire 100 MB again; you simply send a hashed value of the data to the server to check if it has changed. This is what the ETag header is designed for. (see also 304 not modified)
- The remote server never says 'don't use this response after some time'. Instead, it indicates that 'this response will need to be revalidated after a certain period.' However, the client can choose to ignore this. For instance, browsers skip revalidation when there's no internet connection (allow_stale in hishel), which is why you can sometimes browse a website even without Wi-Fi.
- Hishel doesn't do anything on its own; it actually mirrors browser behavior. It has excellent control over cached responses, allowing you to configure the types of responses you want to receive at the request layer. Check out the [directives](https://hishel.com/advanced/http_headers/).

The remote server cannot limit how long the client should store cached responses; this is always configured on the client side. If you want to avoid storing cached responses indefinitely, you can set a time-to-live (TTL). Therefore, there is no such thing as a 'good TTL' in this case, as cached responses never become useless.

I'd be happy to help you with your case if you can provide more information about the types of endpoints you cache and how the caching is configured on the server side.

**Comment by rprodhomme** [comment]
Thanks a lot for your detailed response!

Makes more sense now why the `stale-if-error` is not used in hishel. 

> Anyway, it just specifies how long the response can be used while stale if the remote server responds with a 5xx status code. A very specific case, isn’t it?
That may be a specific use case but that's an important one to have a resilient system.

I think we're good with your answer, we'll set a default ttl (I guess something around one day should be ok for our usage), and use the revalidation as much as possible.

Thanks again for your help!

**Comment by karpetrosyan** [comment]
> stale-if-error is an obsolete directive that should be ignored by new implementations. Please refer to the [latest caching specification](https://www.rfc-editor.org/rfc/rfc9111#name-cache-control) for current directives.

I think I made a mistake here... it's not an obsolete directive. It's an [extension directive](https://www.iana.org/assignments/http-cache-directives/http-cache-directives.xhtml) that can be supported by implementations, and if it can, we should support it. I will try to find time to add such extension support.

There are also other extensions, like stale-while-revalidate and immutable, that we want to support.

**Comment by rprodhomme** [comment]
> > stale-if-error is an obsolete directive that should be ignored by new implementations. Please refer to the [latest caching specification](https://www.rfc-editor.org/rfc/rfc9111#name-cache-control) for current directives.
> 
> I think I made a mistake here... it's not an obsolete directive. It's an [extension directive](https://www.iana.org/assignments/http-cache-directives/http-cache-directives.xhtml) that can be supported by implementations, and if it can, we should support it. I will try to find time to add such extension support.
> 
> There are also other extensions, like stale-while-revalidate and immutable, that we want to support.

Thanks for the follow-up on this, having such a feature would be interesting indeed 👌
